apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service-v1
  namespace: development  # Namespaceを追加
  labels:
    app: weather-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-service
      version: v1
  template:
    metadata:
      labels:
        app: weather-service
        version: v1
    spec:
      containers:
      - name: weather-service
        image: weather-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: OPENWEATHER_API_KEY
          value: "eeb5e018b6a1c71fe75391e7c6342faa"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service-v2
  namespace: development  # Namespaceを追加
  labels:
    app: weather-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
      version: v2
  template:
    metadata:
      labels:
        app: weather-service
        version: v2
    spec:
      containers:
      - name: weather-service
        image: weather-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: OPENWEATHER_API_KEY
          value: "eeb5e018b6a1c71fe75391e7c6342faa"
