apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  labels:
    app: weather-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
      - name: weather-service
        image: weather-app:latest  # MinikubeのローカルDocker環境からイメージを使用
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
       
