apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: development
spec:
  selector:
    app: weather-service
  ports:
  - name: http  # Istioの推奨に従いポート名を追加
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
