apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: weather-service
  namespace: development
spec:
  host: weather-service.development.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      http:
        http1MaxPendingRequests: 1 
        maxRequestsPerConnection: 1