apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weather-service
  namespace: development
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/weather-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: weather-service.development.svc.cluster.local
        subset: v1
        port:
          number: 80
      weight: 0
    - destination:
        host: weather-service.development.svc.cluster.local
        subset: v2
        port:
          number: 80
      weight: 100