apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: weather-service # VirtualServiceの名前
spec:
  hosts:
   - "*" # 任意のホストからトラフィックを受け付ける
   gateways:
   - weather-gateway # Gatewayの名前
   http:
   - match:
      - uri:
          exact: /
      route:
      - destination:
          host: weather-service # トラフィックを転送するPodを選択するためのラベル(Deploymentのmetadataで、labels.appと一致する必要がある)
          port:
            number: 8080
